name: Deploy from two branches

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: Checkout subfolder branch
      uses: actions/checkout@v4
      with:
        ref: 'oldcord'
        path: 'oldcord_temp'

    - name: Setup Pages
      uses: actions/configure-pages@v5
      
    - name: Copy subfolder content
      run: |
        mkdir -p oldcord
        # Копируем содержимое из временной папки в подпапку
        cp -R oldcord_temp/* oldcord/
        # Удаляем временную папку
        rm -rf oldcord_temp

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: .

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
